version: "3.9"

services:
  whisper:
    build: ./whisper
    container_name: whispercpp
    ports:
      - "8000:8000"
    volumes:
      - whisper_tmp:/tmp
    networks:
      - bot_network
    restart: always
  
  ocr:
    build: ./ocr
    container_name: ocr
    ports:
      - "9001:9001"
    volumes:
      - ocr_tmp:/tmp
    networks:
      - bot_network
    restart: always

  bot:
    build: ./bot
    container_name: tg-bot
    env_file:
      - ./bot/.env
    depends_on:
      - whisper
      - ocr
    volumes:
      - bot_logs:/app/logs
      - bot_tmp:/app/tmp
    networks:
      - bot_network
    restart: always

networks:
  bot_network:
    driver: bridge

